# Generated by Django 4.2.2 on 2023-08-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devblogs', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
